site_name: Aplicações de Redes de computadores
site_author: João Paulo
theme:
  name: material
  language: pt

repo_name: PauloMonteiro98/apr-2023-2
repo_ulr: https://github.com/PauloMonteiro98/apr-2023-2